---
# roles/nodejs/vars/debian.yml
# Node.js variables for Debian-based distributions

# Node.js repository configuration
nodejs_repo_key_url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
nodejs_repo_url: "https://deb.nodesource.com/node_{{ nodejs_version }}"

# Package names
nodejs_packages:
  - "nodejs"

# Alternative installation methods for problematic distributions
nodejs_snap_channel: "{{ nodejs_version | regex_replace('\\.x, '') }}/stable"

# NPM configuration
npm_config_prefix: "/usr/local/lib/npm-global"
npm_cache_dir: "/tmp/npm-cache"

# Distribution-specific settings
nodejs_use_snap_for_ubuntu_24: true