---
# roles/nodejs/vars/debian.yml
# Node.js variables for Debian-based distributions

# Node.js installation method
nodejs_installation_method: "repository"  # Options: repository, binary

# Node.js repository configuration
nodejs_repo_key_url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
nodejs_repo_url: "https://deb.nodesource.com/node_{{ nodejs_version }}"

# Package names
nodejs_packages:
  - "nodejs"

# Service configuration (if applicable)
nodejs_service_enabled: false

# NPM configuration
npm_config_prefix: "/usr/local"
npm_cache_dir: "/tmp/npm-cache"