---
# Inventory file

all:
  children:
    webservers:
      hosts:
        webserver1:
          ansible_host: 192.168.1.10
    
    # Example for multiple environments
    staging:
      hosts:
        staging_server:
          ansible_host: 192.168.1.20
    
    production:
      hosts:
        production_server:
          ansible_host: 192.168.1.30
