---
# roles/laravel_webserver/defaults/main.yml
# Default variables for Laravel webserver configuration role

# =============================================================================
# APPLICATION CONFIGURATION
# =============================================================================
# These variables are typically set from the application deployment vars
app_name: ""  # REQUIRED: Application name (used for config files)
webserver_server_name: ""  # REQUIRED: Primary domain name
webserver_server_aliases: []  # Optional domain aliases
webserver_laravel_root: ""  # REQUIRED: Laravel application root directory
webserver_public_root: "{{ webserver_laravel_root }}/public"  # Laravel public directory

# =============================================================================
# WEBSERVER TYPE AND BASIC CONFIGURATION
# =============================================================================
webserver_type: "nginx"  # Options: nginx, apache
webserver_client_max_body_size: "64M"
webserver_enable_ssl: false
webserver_ssl_certificate: ""
webserver_ssl_certificate_key: ""

# =============================================================================
# LARAVEL WEBSERVER FEATURES
# =============================================================================
laravel_webserver_security: true  # Enable security headers and restrictions
laravel_webserver_firewall: false  # Configure UFW firewall rules
laravel_webserver_logging: true  # Separate log files per application
laravel_webserver_caching: true  # Static files caching
laravel_webserver_compression: true  # Enable gzip/deflate compression

# =============================================================================
# SSL/TLS CONFIGURATION
# =============================================================================
laravel_webserver_ssl_protocols: "TLSv1.2 TLSv1.3"
laravel_webserver_ssl_ciphers: "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384"
laravel_webserver_ssl_prefer_server_ciphers: false
laravel_webserver_ssl_session_cache: "shared:SSL:10m"
laravel_webserver_ssl_session_timeout: "10m"
laravel_webserver_ssl_strict: true  # Fail if SSL certificates are missing

# =============================================================================
# SECURITY HEADERS
# =============================================================================
laravel_webserver_security_headers:
  x_frame_options: "SAMEORIGIN"
  x_content_type_options: "nosniff"
  x_xss_protection: "1; mode=block"
  referrer_policy: "strict-origin-when-cross-origin"
  permissions_policy: "geolocation=(), microphone=(), camera=()"

# HSTS (only for HTTPS)
laravel_webserver_hsts_max_age: "31536000"  # 1 year
laravel_webserver_hsts_include_subdomains: true
laravel_webserver_hsts_preload: true

# =============================================================================
# STATIC FILES CACHING
# =============================================================================
laravel_webserver_static_expires: "1y"
laravel_webserver_static_extensions:
  - "css"
  - "js"
  - "png"
  - "jpg"
  - "jpeg"
  - "gif"
  - "ico"
  - "svg"
  - "woff"
  - "woff2"
  - "ttf"
  - "eot"
  - "webp"

# =============================================================================
# PROTECTED LARAVEL DIRECTORIES
# =============================================================================
laravel_webserver_protected_dirs:
  - ".git"
  - ".env"
  - "storage"
  - "bootstrap/cache"
  - "vendor"
  - "node_modules"
  - ".htaccess"
  - "composer.json"
  - "composer.lock"
  - "package.json"

# =============================================================================
# RATE LIMITING (NGINX only)
# =============================================================================
laravel_webserver_rate_limiting: false
laravel_webserver_rate_limit: "10r/s"
laravel_webserver_rate_burst: "20"
laravel_webserver_rate_zone_size: "10m"

# =============================================================================
# CONNECTION LIMITING (Apache only)
# =============================================================================
laravel_webserver_connection_limiting: false
laravel_webserver_max_conn_per_ip: "10"

# =============================================================================
# PHP-FPM INTEGRATION
# =============================================================================
# These are auto-detected but can be overridden
webserver_php_fpm_socket: "unix:/var/run/php/php{{ php_version | default('8.2') }}-fpm.sock"
laravel_webserver_php_timeout: "{{ php_max_execution_time | default('60') }}"
laravel_webserver_php_memory: "{{ php_memory_limit | default('256M') }}"
laravel_webserver_php_upload_size: "{{ php_upload_max_filesize | default('64M') }}"
laravel_webserver_php_post_size: "{{ php_post_max_size | default('64M') }}"

# =============================================================================
# TELESCOPE INTEGRATION
# =============================================================================
laravel_webserver_telescope_restrictions: false
laravel_telescope_path: "telescope"
laravel_telescope_allowed_ips: []
laravel_telescope_require_auth: true

# =============================================================================
# LOGGING CONFIGURATION
# =============================================================================
laravel_webserver_access_log: "/var/log/{{ webserver_type | default('nginx') }}/{{ app_name }}-access.log"
laravel_webserver_error_log: "/var/log/{{ webserver_type | default('nginx') }}/{{ app_name }}-error.log"
laravel_webserver_ssl_access_log: "/var/log/{{ webserver_type | default('nginx') }}/{{ app_name }}-ssl-access.log"
laravel_webserver_ssl_error_log: "/var/log/{{ webserver_type | default('nginx') }}/{{ app_name }}-ssl-error.log"

# =============================================================================
# MAINTENANCE AND BACKUP
# =============================================================================
laravel_webserver_backup_config: true  # Backup existing config before changes
laravel_webserver_validate_config: true  # Test config syntax after changes
laravel_webserver_reload_service: true  # Reload webserver after changes

# =============================================================================
# ADVANCED NGINX SETTINGS
# =============================================================================
laravel_webserver_nginx_worker_connections: "{{ webserver_worker_connections | default('1024') }}"
laravel_webserver_nginx_keepalive_timeout: "{{ webserver_keepalive_timeout | default('65') }}"
laravel_webserver_nginx_gzip: "{{ webserver_gzip | default(true) }}"
laravel_webserver_nginx_gzip_types: "text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript"

# =============================================================================
# ADVANCED APACHE SETTINGS
# =============================================================================
laravel_webserver_apache_keepalive_timeout: "{{ webserver_keepalive_timeout | default('65') }}"
laravel_webserver_apache_max_request_workers: "{{ apache_max_request_workers | default('150') }}"

# =============================================================================
# ERROR HANDLING
# =============================================================================
laravel_webserver_fail_on_ssl_missing: "{{ laravel_webserver_ssl_strict }}"
laravel_webserver_fail_on_config_error: true
laravel_webserver_continue_on_warning: true