---
# roles/laravel_deploy/tasks/pre_configure.yml
# Pre-build configuration tasks - runs BEFORE composer install
# Only includes tasks that don't require vendor/ directory

- name: (pre_configure) Ensure Laravel storage directories exist
  ansible.builtin.file:
    path: "{{ laravel_deploy_path }}/{{ item }}"
    state: directory
    owner: "{{ laravel_deploy_user }}"
    group: "{{ laravel_deploy_group }}"
    mode: '0775'
  loop: "{{ laravel_storage_dirs }}"
  tags: [pre_configure, directories, storage]

- name: (pre_configure) Create basic .env file if it doesn't exist
  ansible.builtin.copy:
    content: |
      APP_NAME={{ laravel_app_name | default(app_name) }}
      APP_ENV={{ laravel_app_env | default('production') }}
      APP_KEY=
      APP_DEBUG={{ laravel_app_debug | default('false') }}
      APP_TIMEZONE={{ php_timezone | default('UTC') }}
      APP_URL={{ laravel_app_url }}
      
      # Database will be configured after build
      DB_CONNECTION={{ laravel_app_db_connection | default('mysql') }}
      DB_HOST={{ laravel_app_db_host | default('127.0.0.1') }}
      DB_PORT={{ laravel_app_db_port | default('3306') }}
      DB_DATABASE={{ laravel_app_db_database | default('laravel') }}
      DB_USERNAME={{ laravel_app_db_username | default('root') }}
      DB_PASSWORD={{ laravel_app_db_password | default('') }}
    dest: "{{ laravel_deploy_path }}/.env"
    owner: "{{ laravel_deploy_user }}"
    group: "{{ laravel_deploy_group }}"
    mode: '0640'
    force: false
  tags: [pre_configure, env]

- name: (pre_configure) Set correct ownership on application files
  ansible.builtin.file:
    path: "{{ laravel_deploy_path }}"
    owner: "{{ laravel_deploy_user }}"
    group: "{{ laravel_deploy_group }}"
    recurse: true
  tags: [pre_configure, permissions]