---
# roles/laravel_deploy/tasks/pre_configure.yml
# Pre-build configuration tasks - runs BEFORE composer install
# Only includes tasks that don't require vendor/ directory

- name: (pre_configure) Ensure Laravel storage directories exist
  ansible.builtin.file:
    path: "{{ laravel_deploy_path }}/{{ item }}"
    state: directory
    owner: "{{ laravel_deploy_user }}"
    group: "{{ laravel_deploy_group }}"
    mode: '0775'
  loop: "{{ laravel_storage_dirs }}"
  tags: [pre_configure, directories, storage]

- name: (pre_configure) Generate Laravel "{{ laravel_deploy_path }}/.env" configuration file
  ansible.builtin.template:
    src: env.j2
    dest: "{{ laravel_deploy_path }}/.env"
    owner: "{{ laravel_deploy_user }}"
    group: "{{ laravel_deploy_group }}"
    mode: '0640'
  notify: Clear Laravel configuration cache
  tags: [config, env]

- name: (pre_configure) Set correct ownership on application files
  ansible.builtin.file:
    path: "{{ laravel_deploy_path }}"
    owner: "{{ laravel_deploy_user }}"
    group: "{{ laravel_deploy_group }}"
    recurse: true
  tags: [pre_configure, permissions]