---
# roles/webserver/vars/redhat.yml
# Webserver variables for RHEL-based distributions

# NGINX
nginx_packages:
  - "nginx"
nginx_service: "nginx"
nginx_user: "nginx"
nginx_group: "nginx"
nginx_conf_path: "/etc/nginx/nginx.conf"
nginx_vhost_dir: "/etc/nginx/conf.d"
nginx_enabled_vhost_dir: "/etc/nginx/conf.d"
nginx_default_vhost_path: "/etc/nginx/conf.d/default.conf"

# Apache
apache_packages:
  - "httpd"
  - "mod_ssl"
apache_service: "httpd"
apache_user: "apache"
apache_group: "apache"
apache_conf_path: "/etc/httpd/conf/httpd.conf"
apache_vhost_dir: "/etc/httpd/conf.d"
apache_enabled_vhost_dir: "/etc/httpd/conf.d"
apache_default_vhost_path: "/etc/httpd/conf.d/welcome.conf"
apache_modules: []  # Modules are typically loaded via the conf files in RHEL

# Common
webserver_user: "{{ (webserver_type == 'nginx') | ternary(nginx_user, apache_user) }}"
webserver_group: "{{ (webserver_type == 'nginx') | ternary(nginx_group, apache_group) }}"