---
# roles/nodejs/vars/default.yml
# Default Node.js variables for unsupported distributions

# Node.js installation method
nodejs_installation_method: "binary"  # Fallback to binary installation

# Package names (empty for binary installation)
nodejs_packages: []

# Service configuration
nodejs_service_enabled: false

# NPM configuration
npm_config_prefix: "/usr/local"
npm_cache_dir: "/tmp/npm-cache"

# Binary installation settings
nodejs_binary_url: "https://nodejs.org/dist/v{{ nodejs_version | regex_replace('\\.x$', '.0') }}/node-v{{ nodejs_version | regex_replace('\\.x$', '.0') }}-linux-x64.tar.xz"
nodejs_binary_install_dir: "/opt/nodejs"