---
# roles/mariadb/tasks/configure.yml
# MariaDB configuration tasks

- name: (configure) Copy MariaDB configuration file
  ansible.builtin.template:
    src: mariadb.cnf.j2
    dest: "{{ mariadb_config_file }}"
    owner: root
    group: root
    mode: '0644'
  notify: Restart MariaDB
  tags: [mariadb, configure]

- name: (configure) Create MariaDB database for Laravel if specified
  ansible.builtin.mysql_db:
    name: "{{ mariadb_db_name }}"
    state: present
    login_user: root
    login_password: "{{ mariadb_root_password }}"
    encoding: "{{ mariadb_db_encoding }}"
    collation: "{{ mariadb_db_collation }}"
  when: 
    - mariadb_db_name is defined
    - mariadb_db_name != ''
    - mariadb_root_password is defined
    - mariadb_root_password != ''
  tags: [mariadb, configure]

- name: (configure) Create MariaDB user for Laravel if specified
  ansible.builtin.mysql_user:
    name: "{{ mariadb_db_user }}"
    password: "{{ mariadb_db_password }}"
    priv: "{{ mariadb_db_name }}.*:ALL"
    host: "{{ mariadb_db_host | default('%') }}"
    state: present
    login_user: root
    login_password: "{{ mariadb_root_password }}"
  when: 
    - mariadb_db_name is defined 
    - mariadb_db_name != ''
    - mariadb_db_user is defined
    - mariadb_db_user != ''
    - mariadb_db_password is defined
    - mariadb_db_password != ''
    - mariadb_root_password is defined
    - mariadb_root_password != ''
  no_log: true
  tags: [mariadb, configure]