---
# roles/mysql/tasks/install.yml
# MySQL installation tasks

- name: (install) Set distribution-specific variables
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_os_family | lower }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution | lower }}.yml"
    - "{{ ansible_os_family | lower }}.yml"
    - "default.yml"
  tags: [mysql, install]

# Debian/Ubuntu
- name: (install) Install MySQL (Debian/Ubuntu)
  ansible.builtin.apt:
    name: "{{ mysql_packages }}"
    state: present
    update_cache: true
  when: ansible_os_family == 'Debian'
  tags: [mysql, install]

# RHEL/CentOS
- name: (install) Install MySQL (RHEL/CentOS)
  block:
    - name: (install) Install MySQL repository
      ansible.builtin.dnf:
        name: "{{ mysql_repo_package }}"
        state: present
      when: mysql_repo_package is defined

    - name: (install) Install MySQL packages
      ansible.builtin.dnf:
        name: "{{ mysql_packages }}"
        state: present
  when: ansible_os_family == 'RedHat'
  tags: [mysql, install]

# Common tasks
- name: (install) Ensure MySQL service is running and enabled
  ansible.builtin.service:
    name: "{{ mysql_service }}"
    state: started
    enabled: true
  tags: [mysql, install]

# Check if MySQL root password is already set
- name: (install) Check if MySQL root password is set
  ansible.builtin.command: >
    mysql -u root -e "SELECT 1"
  register: mysql_root_password_check
  ignore_errors: true
  changed_when: false
  no_log: true
  tags: [mysql, install]

# Set root password only if it's not already set and a password is provided
- name: (install) Set MySQL root password (first time setup)
  ansible.builtin.command: >
    mysqladmin -u root password "{{ mysql_root_password }}"
  when: 
    - mysql_root_password is defined 
    - mysql_root_password != ''
    - mysql_root_password_check.rc == 0  # No password currently set
  register: mysql_root_password_update
  changed_when: mysql_root_password_update.rc == 0
  failed_when: mysql_root_password_update.rc != 0 and mysql_root_password_update.rc != 1
  no_log: true
  tags: [mysql, install]

# Change root password if current password is provided
- name: (install) Change MySQL root password (password update)
  ansible.builtin.command: >
    mysqladmin -u root -p"{{ mysql_root_password_current }}" password "{{ mysql_root_password }}"
  when: 
    - mysql_root_password is defined 
    - mysql_root_password != ''
    - mysql_root_password_current is defined
    - mysql_root_password_current != ''
    - mysql_root_password_check.rc != 0  # Password is already set
  register: mysql_root_password_change
  changed_when: mysql_root_password_change.rc == 0
  failed_when: mysql_root_password_change.rc != 0 and mysql_root_password_change.rc != 1
  no_log: true
  tags: [mysql, install]

- name: (install) Copy .my.cnf file with root password credentials
  ansible.builtin.template:
    src: root-my.cnf.j2
    dest: /root/.my.cnf
    owner: root
    group: root
    mode: '0600'
  when: mysql_root_password is defined and mysql_root_password != ''
  tags: [mysql, install]

- name: (install) Delete anonymous MySQL users
  community.mysql.mysql_user:
    name: ''
    host_all: true
    state: absent
    login_user: root
    login_password: "{{ mysql_root_password }}"
  when: mysql_root_password is defined and mysql_root_password != ''
  ignore_errors: true  # Might fail if users don't exist
  tags: [mysql, install]

- name: (install) Remove test database
  community.mysql.mysql_db:
    name: test
    state: absent
    login_user: root
    login_password: "{{ mysql_root_password }}"
  when: mysql_root_password is defined and mysql_root_password != ''
  ignore_errors: true  # Might fail if database doesn't exist
  tags: [mysql, install]