---
# roles/mysql/tasks/install.yml
# MySQL installation tasks - Fixed for MySQL 8.0 auth_socket issue

- name: (install) Set distribution-specific variables
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_os_family | lower }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution | lower }}.yml"
    - "{{ ansible_os_family | lower }}.yml"
    - "default.yml"
  tags: [mysql, install]

# Debian/Ubuntu
- name: (install) Install MySQL (Debian/Ubuntu)
  ansible.builtin.apt:
    name: "{{ mysql_packages }}"
    state: present
    update_cache: true
  when: ansible_os_family == 'Debian'
  tags: [mysql, install]

# RHEL/CentOS
- name: (install) Install MySQL (RHEL/CentOS)
  block:
    - name: (install) Install MySQL repository
      ansible.builtin.dnf:
        name: "{{ mysql_repo_package }}"
        state: present
      when: mysql_repo_package is defined

    - name: (install) Install MySQL packages
      ansible.builtin.dnf:
        name: "{{ mysql_packages }}"
        state: present
  when: ansible_os_family == 'RedHat'
  tags: [mysql, install]

# Common tasks
- name: (install) Ensure MySQL service is running and enabled
  ansible.builtin.service:
    name: "{{ mysql_service }}"
    state: started
    enabled: true
  tags: [mysql, install]

# Fix for MySQL 8.0 auth_socket plugin on Ubuntu
- name: (install) Check MySQL authentication method for root user
  ansible.builtin.shell: |
    mysql -e "SELECT user, host, plugin FROM mysql.user WHERE user='root'" | grep auth_socket || true
  register: mysql_auth_check
  changed_when: false
  ignore_errors: true
  tags: [mysql, install]

- name: (install) Set MySQL root password and change authentication plugin (MySQL 8.0)
  ansible.builtin.shell: |
    mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '{{ mysql_root_password }}';"
    mysql -e "FLUSH PRIVILEGES;"
  when: 
    - mysql_root_password is defined 
    - mysql_root_password != ''
    - "'auth_socket' in mysql_auth_check.stdout"
  register: mysql_root_password_update
  changed_when: true
  no_log: true
  tags: [mysql, install]

# For systems where root doesn't use auth_socket
- name: (install) Check if MySQL root password is already set (traditional method)
  ansible.builtin.command: >
    mysql -u root -e "SELECT 1"
  register: mysql_root_password_check
  ignore_errors: true
  changed_when: false
  no_log: true
  when: "'auth_socket' not in mysql_auth_check.stdout"
  tags: [mysql, install]

- name: (install) Set MySQL root password (first time setup - traditional)
  ansible.builtin.command: >
    mysqladmin -u root password "{{ mysql_root_password }}"
  when: 
    - mysql_root_password is defined 
    - mysql_root_password != ''
    - "'auth_socket' not in mysql_auth_check.stdout"
    - mysql_root_password_check is defined
    - mysql_root_password_check.rc == 0
  register: mysql_root_password_update_traditional
  changed_when: mysql_root_password_update_traditional.rc == 0
  failed_when: mysql_root_password_update_traditional.rc != 0 and mysql_root_password_update_traditional.rc != 1
  no_log: true
  tags: [mysql, install]

- name: (install) Copy .my.cnf file with root password credentials
  ansible.builtin.template:
    src: root-my.cnf.j2
    dest: /root/.my.cnf
    owner: root
    group: root
    mode: '0600'
  when: mysql_root_password is defined and mysql_root_password != ''
  tags: [mysql, install]

# Security cleanup - now that we have proper authentication
- name: (install) Delete anonymous MySQL users
  community.mysql.mysql_user:
    name: ''
    host_all: true
    state: absent
    login_user: root
    login_password: "{{ mysql_root_password }}"
  when: mysql_root_password is defined and mysql_root_password != ''
  ignore_errors: true
  tags: [mysql, install]

- name: (install) Remove MySQL test database
  community.mysql.mysql_db:
    name: test
    state: absent
    login_user: root
    login_password: "{{ mysql_root_password }}"
  when: mysql_root_password is defined and mysql_root_password != ''
  ignore_errors: true
  tags: [mysql, install]

# Remove root access from remote hosts for security
- name: (install) Remove remote root access
  community.mysql.mysql_user:
    name: root
    host: "{{ item }}"
    state: absent
    login_user: root
    login_password: "{{ mysql_root_password }}"
  loop:
    - "%"
    - "127.0.0.1"
    - "::1"
    - "{{ ansible_hostname }}"
  when: mysql_root_password is defined and mysql_root_password != ''
  ignore_errors: true
  tags: [mysql, install]