---
# roles/composer/tasks/configure.yml
# Composer configuration tasks

- name: (configure) Set GitHub OAuth token if provided
  ansible.builtin.command: composer config -g github-oauth.github.com {{ composer_github_oauth_token }}
  when: composer_github_oauth_token is defined and composer_github_oauth_token != ''
  changed_when: true
  tags: [composer, configure]

- name: (configure) Set global config values
  ansible.builtin.command: composer config -g {{ item.key }} {{ item.value }}
  with_items: "{{ composer_global_configs }}"
  changed_when: true
  when: composer_global_configs | length > 0
  tags: [composer, configure]
  
- name: (configure) Create Composer cache directory
  ansible.builtin.file:
    path: "{{ composer_home_dir }}/cache"
    state: directory
    mode: '0755'
  tags: [composer, configure]

- name: (configure) Install global Composer packages if specified
  ansible.builtin.command: composer global require {{ item }}
  loop: "{{ composer_global_packages }}"
  when: composer_global_packages | length > 0
  register: composer_global_result
  changed_when: "'Nothing to install, update or remove' not in composer_global_result.stdout"
  tags: [composer, configure]