---
# roles/composer/tasks/install.yml
# Composer installation tasks

- name: (install) Check if Composer is installed
  ansible.builtin.command: composer --version
  register: composer_version_check
  ignore_errors: true
  changed_when: false
  check_mode: false
  tags: [composer, install]

- name: (install) Download Composer installer
  ansible.builtin.get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/composer-setup.php
    mode: '0755'
  when: composer_version_check.rc != 0 or 'composer.phar' in composer_version_check.stdout
  tags: [composer, install]

- name: (install) Install Composer
  ansible.builtin.command: >
    php /tmp/composer-setup.php
    --install-dir=/usr/local/bin
    --filename=composer
  args:
    creates: /usr/local/bin/composer
  when: composer_version_check.rc != 0 or 'composer.phar' in composer_version_check.stdout
  tags: [composer, install]

- name: (install) Verify Composer installation
  ansible.builtin.command: composer --version
  register: composer_version_result
  changed_when: false
  check_mode: false
  tags: [composer, install]

- name: (install) Display installed Composer version
  ansible.builtin.debug:
    msg: "Installed Composer version: {{ composer_version_result.stdout }}"
  tags: [composer, install]