---
# roles/redis/defaults/main.yml
# Default variables for Redis role

# Redis version
redis_version: "7.0"

# Redis configuration
redis_port: 6379
redis_bind_address: "127.0.0.1"
redis_unixsocket: ""
redis_timeout: 0

# Redis memory settings
redis_maxmemory: "256mb"
redis_maxmemory_policy: "noeviction"
redis_maxmemory_samples: 5

# Redis persistence
redis_save:
  - "900 1"
  - "300 10"
  - "60 10000"
redis_rdbcompression: "yes"
redis_dbfilename: "dump.rdb"

# Redis security
redis_requirepass: ""
redis_disable_commands: []

# Redis performance tuning
redis_databases: 16
redis_tcp_backlog: 511
redis_tcp_keepalive: 300
redis_loglevel: "notice"

# Redis directories
redis_dir: "/var/lib/redis"
redis_data_dir: "/var/lib/redis"
redis_log_dir: "/var/log/redis"

# Redis system tuning
redis_enable_vm_overcommit_memory: true
redis_disable_transparent_hugepages: true