---
# roles/postgresql/defaults/main.yml
# Default variables for PostgreSQL role

# PostgreSQL version
postgresql_version: "15"

# PostgreSQL admin password
postgresql_admin_password: ""

# PostgreSQL database for Laravel
postgresql_db_name: "laravel"
postgresql_db_user: "laravel"
postgresql_db_password: ""
postgresql_db_encoding: "UTF8"
postgresql_db_lc_collate: "en_US.UTF-8"
postgresql_db_lc_ctype: "en_US.UTF-8"

# PostgreSQL configuration
postgresql_listen_addresses: "localhost"
postgresql_port: 5432
postgresql_max_connections: 100
postgresql_shared_buffers: "128MB"
postgresql_work_mem: "4MB"
postgresql_maintenance_work_mem: "64MB"
postgresql_effective_cache_size: "4GB"
postgresql_max_wal_size: "1GB"
postgresql_min_wal_size: "80MB"
postgresql_wal_buffers: "16MB"
postgresql_checkpoint_completion_target: 0.7
postgresql_random_page_cost: 4.0
postgresql_effective_io_concurrency: 2

# Client authentication
postgresql_hba_entries:
  - type: local
    database: all
    user: postgres
    auth_method: peer
  - type: local
    database: all
    user: all
    auth_method: md5
  - type: host
    database: all
    user: all
    address: 127.0.0.1/32
    auth_method: md5
  - type: host
    database: all
    user: all
    address: ::1/128
    auth_method: md5