---
# roles/webserver/tasks/nginx_configure.yml
# NGINX configuration tasks

- name: (nginx_configure) Configure NGINX global settings
  ansible.builtin.template:
    src: nginx/nginx.conf.j2
    dest: "{{ nginx_conf_path }}"
    owner: root
    group: root
    mode: '0644'
  notify: Restart NGINX
  tags: [webserver, nginx, configure]

- name: (nginx_configure) Create NGINX server block directory
  ansible.builtin.file:
    path: "{{ nginx_vhost_dir }}"
    state: directory
    owner: root
    group: root
    mode: '0755'
  tags: [webserver, nginx, configure]

- name: (nginx_configure) Configure NGINX Laravel server block
  ansible.builtin.template:
    src: nginx/laravel.conf.j2
    dest: "{{ nginx_vhost_dir }}/{{ webserver_server_name }}.conf"
    owner: root
    group: root
    mode: '0644'
  notify: Restart NGINX
  when: webserver_server_name is defined and webserver_server_name != ''
  tags: [webserver, nginx, configure]