---
# roles/php/defaults/main.yml
# Default PHP configurations for Laravel

# PHP Version (will be overridden by group_vars)
php_version: "8.2"

# PHP Memory Limits
php_memory_limit: "128M"
php_post_max_size: "64M"
php_upload_max_filesize: "64M"

# PHP Execution Time Limits
php_max_execution_time: 60
php_max_input_time: 60

# PHP Timezone (set to UTC by default)
#php_timezone: "UTC"
php_timezone: "Europe/Paris"

# PHP Opcache Settings
php_opcache_enable: 1
php_opcache_memory_consumption: 128
php_opcache_interned_strings_buffer: 16
php_opcache_max_accelerated_files: 10000
php_opcache_validate_timestamps: 1
php_opcache_revalidate_freq: 2
php_opcache_enable_cli: 1

# PHP-FPM Pool Settings
php_fpm_pm: dynamic
php_fpm_max_children: 50
php_fpm_start_servers: 5
php_fpm_min_spare_servers: 5
php_fpm_max_spare_servers: 35
php_fpm_max_requests: 500

# Custom PHP settings
php_custom_settings: []
  # Example:
  # - key: "display_errors"
  #   value: "Off"